id = "mbc"
name = "MBC"
version = "0.1.1"
schema_version = 1
authors = ["Jakub B, Adam P w/ Codex and GH Copilot"]
description = "MBC language support for Zed"
repository = "https://github.com/bravajak/zed-mbc"

[grammars.mbc]
repository = "https://github.com/bravajak/zed-mbc.git"
rev = "main"
path = "."
